In [1]:
import numpy as np 
import pandas as pd 
inputdata = pd.read_csv('NYC_Crime_Cleaned.csv')

In [2]:
target = inputdata["Offence_Type"].unique()

In [3]:
data_dict = {}
count = 1
for data in target:
    data_dict[data] = count
    count = count + 1
inputdata["Offence_Type"] = inputdata["Offence_Type"].replace(data_dict)

In [4]:
inputdata['Start_Date'] = pd.to_datetime(inputdata['Start_Date'])

In [5]:
inputdata['day_of_week'] = inputdata['Start_Date'].dt.day_name()

In [6]:
inputdata['day_of_week'].unique()

array(['Sunday', 'Saturday', 'Friday', 'Thursday', 'Wednesday', 'Tuesday',
       'Monday'], dtype=object)

In [7]:
district = inputdata["Offence_Level"].unique()
data_dict_district = {}
count = 1
for data in district:
    data_dict_district[data] = count
    count+=1
inputdata["Offence_Level"] = inputdata["Offence_Level"].replace(data_dict_district).dropna()

In [8]:
inputdata

Complaint_ID                Start_Date Start_Time  Neighborhood  \
0           849484321 2011-11-27 00:00:00+00:00   00:02:00          14.0   
1           201779846 2011-11-27 00:00:00+00:00   00:01:00         113.0   
2           528511042 2011-11-27 00:00:00+00:00   00:01:00          10.0   
3           741313529 2011-11-27 00:00:00+00:00   00:01:00          70.0   
4           517952221 2011-11-27 00:00:00+00:00   00:00:00          23.0   
5           888361194 2011-11-27 00:00:00+00:00   00:00:00          88.0   
6           211551597 2011-11-27 00:00:00+00:00   00:00:00         100.0   
7           482588995 2011-11-27 00:00:00+00:00   00:00:00          18.0   
8           997922834 2011-11-26 00:00:00+00:00   23:59:00          94.0   
9           220891615 2011-11-26 00:00:00+00:00   23:58:00          43.0   
10          331893950 2011-11-26 00:00:00+00:00   23:58:00         115.0   
11          367835683 2011-11-26 00:00:00+00:00   23:55:00          73.0   
12          616879973 2011-11-26 00:00:00+00:00   23:55:00         120.0   
13          587598699 2011-11-26 00:00:00+00:00   23:50:00          42.0   
14          262364691 2011-11-26 00:00:00+00:00   23:50:00          42.0   
15          158917420 2011-11-26 00:00:00+00:00   23:50:00          42.0   
16          627711444 2011-11-20 00:00:00+00:00   17:28:00          44.0   
17          510463237 2011-11-26 00:00:00+00:00   23:50:00          42.0   
18          325590321 2011-11-26 00:00:00+00:00   23:50:00          42.0   
19          840831794 2011-11-26 00:00:00+00:00   23:50:00          42.0   
20          691277763 2011-11-26 00:00:00+00:00   23:50:00          76.0   
21          565042303 2011-11-26 00:00:00+00:00   23:50:00          83.0   
22          238812144 2011-11-26 00:00:00+00:00   23:50:00         105.0   
23          967204946 2011-11-26 00:00:00+00:00   23:50:00         122.0   
24          955238299 2011-11-26 00:00:00+00:00   23:47:00          52.0   
25          358168582 2011-11-26 00:00:00+00:00   23:45:00          40.0   
26          119316651 2011-11-26 00:00:00+00:00   23:45:00          46.0   
27          457933985 2011-11-26 00:00:00+00:00   23:45:00          46.0   
28          589023478 2011-11-26 00:00:00+00:00   23:45:00         115.0   
29          774755690 2011-11-26 00:00:00+00:00   23:44:00          48.0   
...               ...                       ...        ...           ...   
6017023     169058890 2011-11-27 00:00:00+00:00   00:35:00          43.0   
6017024     330114043 2011-11-27 00:00:00+00:00   00:30:00          42.0   
6017025     577109494 2011-11-27 00:00:00+00:00   00:30:00          44.0   
6017026     342445130 2011-11-27 00:00:00+00:00   00:30:00          60.0   
6017027     153850866 2011-11-27 00:00:00+00:00   00:30:00          66.0   
6017028     571495358 2011-11-27 00:00:00+00:00   00:30:00          71.0   
6017029     774780387 2011-11-27 00:00:00+00:00   00:30:00          79.0   
6017030     479354226 2011-11-27 00:00:00+00:00   00:30:00           7.0   
6017031     792070006 2011-11-27 00:00:00+00:00   00:30:00          70.0   
6017032     546300062 2011-11-27 00:00:00+00:00   00:30:00          90.0   
6017033     591439063 2011-11-27 00:00:00+00:00   00:30:00          43.0   
6017034     158680970 2011-11-27 00:00:00+00:00   00:27:00          40.0   
6017035     768297553 2011-11-27 00:00:00+00:00   00:25:00          33.0   
6017036     963981477 2011-11-27 00:00:00+00:00   00:21:00           1.0   
6017037     314028272 2011-11-27 00:00:00+00:00   00:21:00           1.0   
6017038     665529587 2011-11-27 00:00:00+00:00   00:20:00          60.0   
6017039     528116203 2011-11-27 00:00:00+00:00   00:20:00          60.0   
6017040     979846689 2011-11-27 00:00:00+00:00   00:20:00          67.0   
6017041     231086927 2011-11-27 00:00:00+00:00   00:18:00          26.0   
6017042     750153027 2011-11-27 00:00:00+00:00   00:15:00          41.0   
6017043     384645813 2011-11-27 00:00:00+00:00   00:15:0

In [9]:
inputdata = inputdata[['day_of_week','Latitude','Longitude','Offence_Level','Neighborhood','Borough']]

In [10]:
days = {'Monday':0,'Tuesday':1,'Wednesday':2,'Thursday':3,'Friday':4,'Saturday':5,'Sunday':6}
inputdata['day_of_week'] = inputdata['day_of_week'].apply(lambda x: days[x])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [11]:
inputdata = inputdata.dropna()

In [12]:
cat = ['day_of_week','Borough']
dummie = pd.get_dummies(inputdata[cat])

In [13]:
inputdata = pd.concat([dummie,inputdata[['Latitude','Longitude','Offence_Level','Neighborhood']]],axis = 1)

In [14]:
from sklearn import linear_model, neighbors, preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
dummie_maxmin = min_max_scaler.fit_transform(inputdata.drop('Offence_Level',axis=1))

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [15]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, train_test_split, cross_val_score
X_train,X_test, y_train, y_test = train_test_split(inputdata.drop('Offence_Level',axis=1),inputdata['Offence_Level'],test_size=0.3,random_state=1)

In [16]:
X_train = X_train.values
X_test = X_test.values 
y_train = y_train.values
y_test = y_test.values

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 30)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
predictions

array([1, 1, 1, ..., 2, 1, 1])

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,predictions)

0.5590719119142067

In [21]:
cm = confusion_matrix(predictions,y_test)
cm

array([[930265, 475748, 200106],
       [ 90133,  72412,  21366],
       [  3464,   1600,   2063]])

In [25]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100,random_state=0,criterion='gini',class_weight='balanced')
clf.fit(X_train,y_train)
y_predict = clf.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_predict)

0.4181326394967162

In [27]:
cm = confusion_matrix(y_predict,y_test)
cm

array([[453069, 200116,  71561],
       [295154, 205867,  59460],
       [275639, 143777,  92514]])